In [2]:
import pandas as pd
import duckdb as db
import os
import xlrd

In [3]:
cwd = os.getcwd()

In [4]:
cwd

'C:\\Users\\jacks\\Documents\\GitHub\\MBB_Shiny_Dashboard\\Jupyter_Files'

In [5]:
begin_dir = 'C:\\Users\\jacks\\Documents\\GitHub\MBB_Shiny_Dashboard\\'
begin_dir

'C:\\Users\\jacks\\Documents\\GitHub\\MBB_Shiny_Dashboard\\'

In [6]:
MBB_Team_totals = pd.read_csv('C:\\Users\\jacks\\Documents\\GitHub\\MBB_Shiny_Dashboard\\Source_Data\\MBB_Team_totals.csv')
MBB_Team_totals = MBB_Team_totals.drop(columns=['W.1', 'Rk', 'MP'])
MBB_Team_totals

,Season,Team,W,G,L,W/L%,Team Total FG,Team Total FGA,Team Total 2P,Team Total 2PA,...,Team Total BLK,Team Total TOV,Team Total PF,Team Total PTS,Team Shooting Total FG%,Team Shooting Total 2P%,Team Shooting Total 3P%,Team Shooting Total FT%,Team Shooting Total TS%,Team Shooting Total eFG%
0,2023-24,Connecticut,37,40,3,0.925,1177,2367,837,1416,...,217,383,650,3256,0.497,0.591,0.358,0.743,0.597,0.569
1,2023-24,Purdue,34,39,5,0.872,1109,2272,791,1484,...,142,442,536,3211,0.488,0.533,0.404,0.720,0.591,0.558
2,2023-24,Houston,32,37,5,0.865,981,2233,695,1412,...,178,330,658,2720,0.439,0.492,0.348,0.687,0.531,0.503
3,2023-24,Indiana State,32,39,7,0.821,1141,2258,714,1139,...,72,452,638,3309,0.505,0.627,0.382,0.796,0.632,0.600
4,2023-24,James Madison,32,36,4,0.889,1073,2254,766,1402,...,113,392,621,2995,0.476,0.546,0.360,0.703,0.572,0.544
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,2023-24,VMI,4,32,28,0.125,818,1935,608,1262,...,82,507,539,2204,0.423,0.482,0.312,0.692,0.505,0.477
358,2023-24,DePaul,3,32,29,0.094,725,1714,525,1117,...,99,435,482,2071,0.423,0.470,0.335,0.733,0.521,0.481
359,2023-24,Coppin State,2,29,27,0.069,585,1571,432,1031,...,81,455,513,1678,0.372,0.419,0.283,0.726,0.465,0.421
360,2023-24,Detroit Mercy,1,32,31,0.031,761,1806,574,1140,...,78,427,553,2111,0.421,0.504,0.281,0.735,0.511,0.473
361,2023-24,Mississippi Valley State,1,31,30,0.032,613,1611,470,1122,...,71,495,550,1719,0.381,0.419,0.292,0.658,0.461,0.425

In [7]:
MBB_Team_totals_in_NCAAT = pd.read_csv('C:\\Users\\jacks\\Documents\\GitHub\\MBB_Shiny_Dashboard\\Source_Data\\MBB_Team_totals_in_NCAAT.csv')
MBB_Team_totals_in_NCAAT = MBB_Team_totals_in_NCAAT.drop(columns=['W', 'G', 'L', 'W/L%', 'W.1', 'Rk', 'MP'])
made_tournament = MBB_Team_totals_in_NCAAT['Team'].tolist()

In [8]:
MBB_Team_Opponent_per_game = pd.read_csv('C:\\Users\\jacks\\Documents\\GitHub\\MBB_Shiny_Dashboard\\Source_Data\\MBB_Team_Opponent_per_Game.csv')
MBB_Team_Opponent_per_game = MBB_Team_Opponent_per_game.drop(columns=['W', 'G', 'L', 'W/L%', 'W.1', 'Rk', 'MP'])
MBB_Team_Opponent_per_game

,Season,Team,Team FG,Team FGA,Team 2P,Team 2PA,Team 3P,Team 3PA,Team FT,Team FTA,...,Opponent FTA,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Opponent PTS
0,2023-24,Connecticut,29.4,59.2,20.9,35.4,8.5,23.8,14.1,18.9,...,17.7,9.9,20.2,30.1,10.0,5.4,3.0,10.6,16.6,63.4
1,2023-24,Purdue,28.4,58.3,20.3,38.1,8.2,20.2,17.3,24.1,...,13.7,9.1,20.2,29.3,14.2,6.7,2.5,9.4,20.3,69.0
2,2023-24,Houston,26.5,60.4,18.8,38.2,7.7,22.2,12.8,18.6,...,19.8,10.8,23.1,33.8,11.4,5.0,2.8,15.8,16.2,57.6
3,2023-24,Indiana State,29.3,57.9,18.3,29.2,10.9,28.7,15.4,19.3,...,16.0,8.7,23.3,31.9,10.9,6.2,3.3,11.2,17.1,73.2
4,2023-24,James Madison,29.8,62.6,21.3,38.9,8.5,23.7,15.1,21.4,...,20.0,9.9,24.0,33.9,10.7,5.9,3.4,14.3,17.3,69.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,2023-24,VMI,25.6,60.5,19.0,39.4,6.6,21.0,11.2,16.2,...,19.6,11.3,27.8,39.1,15.3,9.1,3.2,11.7,15.8,82.6
358,2023-24,DePaul,22.7,53.6,16.4,34.9,6.3,18.7,13.2,17.9,...,17.3,10.7,25.8,36.5,17.3,7.7,3.6,9.9,16.8,81.8
359,2023-24,Coppin State,20.2,54.2,14.9,35.6,5.3,18.6,12.2,16.9,...,21.3,12.8,26.3,39.1,14.6,8.9,3.4,14.9,15.7,72.8
360,2023-24,Detroit Mercy,23.8,56.4,17.9,35.6,5.8,20.8,12.6,17.1,...,18.7,11.3,25.3,36.6,15.1,6.2,3.1,11.9,16.1,80.3
361,2023-24,Mississippi Valley State,19.8,52.0,15.2,36.2,4.6,15.8,11.3,17.2,...,22.9,11.0,24.9,35.8,14.6,8.8,3.2,11.4,16.7,77.7

In [9]:
MBB_Opponent_Totals = pd.read_csv('C:\\Users\\jacks\\Documents\\GitHub\\MBB_Shiny_Dashboard\\Source_Data\\MBB_Opponents_Totals.csv')
MBB_Opponent_Totals = MBB_Opponent_Totals.drop(columns=['W', 'G', 'L', 'W/L%', 'W.1', 'Rk'])
MBB_Opponent_Totals

,Season,Team,Opponent Total FG,Opponent Total FGA,Opponent Total 2P,Opponent Total 2PA,Opponent Total 3P,Opponent Total 3PA,Opponent Total FT,Opponent Total FTA,...,Opponent Total AST,Opponent Total STL,Opponent Total BLK,Opponent Total TOV,Opponent Total PF,Opponent Total PTS,Opponent Shooting Total FG%,Opponent Shooting Total 2P%,Opponent Shooting Total 3P%,Opponent Shooting Total FT%
0,2023-24,Connecticut,894,2278,660,1529,234,749,514,709,...,400,214,118,422,663,2536,0.392,0.432,0.312,0.725
1,2023-24,Purdue,1011,2423,730,1530,281,893,386,534,...,555,263,96,368,792,2691,0.417,0.477,0.315,0.723
2,2023-24,Houston,706,1862,481,1115,225,747,495,734,...,422,186,102,585,599,2132,0.379,0.431,0.301,0.674
3,2023-24,Indiana State,1055,2406,773,1587,282,819,462,624,...,424,241,130,437,665,2854,0.438,0.487,0.344,0.740
4,2023-24,James Madison,878,2112,653,1359,225,753,525,721,...,385,214,123,516,621,2506,0.416,0.481,0.299,0.728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,2023-24,VMI,969,2092,676,1271,293,821,413,628,...,491,292,101,375,507,2644,0.463,0.532,0.357,0.658
358,2023-24,DePaul,949,1948,644,1147,305,801,413,554,...,552,246,114,318,539,2616,0.487,0.561,0.381,0.745
359,2023-24,Coppin State,723,1613,514,1007,209,606,457,618,...,424,259,98,431,455,2112,0.448,0.510,0.345,0.739
360,2023-24,Detroit Mercy,921,1878,662,1179,259,699,467,599,...,482,197,98,380,515,2568,0.490,0.561,0.371,0.780
361,2023-24,Mississippi Valley State,835,1711,604,1087,231,624,508,711,...,452,273,98,354,519,2409,0.488,0.556,0.370,0.714

In [10]:
MBB_Team_Advanced = pd.read_csv('C:\\Users\\jacks\\Documents\\GitHub\\MBB_Shiny_Dashboard\\Source_Data\\MBB_Season_Advanced.csv')
MBB_Team_Advanced = MBB_Team_Advanced.drop(columns=['W', 'G', 'L', 'W/L%', 'W.1', 'Rk'])
MBB_Team_Advanced

,Season,Team,Miscellaneous Pace,Miscellaneous ORtg,Miscellaneous DRtg,Team Shooting eFG%,Team Shooting TS%,Team TOV%,Team ORB%,Team DRB%,Team FTr,Opponent Shooting eFG%,Opponent Shooting TS%,Opponent TOV%,Opponent ORB%,Opponent DRB%,Opponent FTr
0,2023-24,Connecticut,66.0,123.3,96.0,0.569,0.597,12.3,36.7,73.3,0.319,0.444,0.485,13.9,26.7,63.3,0.311
1,2023-24,Purdue,68.3,119.5,100.1,0.558,0.591,14.0,37.7,75.7,0.413,0.475,0.503,12.1,24.3,62.3,0.220
2,2023-24,Houston,64.1,113.6,89.0,0.503,0.531,11.4,36.8,68.8,0.308,0.440,0.482,20.9,31.2,63.2,0.394
3,2023-24,Indiana State,71.4,118.4,102.1,0.600,0.632,14.7,23.5,76.6,0.334,0.497,0.528,13.9,23.4,76.5,0.259
4,2023-24,James Madison,71.6,115.0,96.2,0.544,0.572,13.0,32.5,73.1,0.342,0.469,0.510,17.4,26.9,67.5,0.341
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,2023-24,VMI,74.6,92.0,110.3,0.477,0.505,18.9,25.2,70.7,0.267,0.533,0.553,13.6,29.3,74.8,0.300
358,2023-24,DePaul,68.4,94.7,119.6,0.481,0.521,18.0,22.0,67.7,0.335,0.565,0.592,12.6,32.3,78.0,0.284
359,2023-24,Coppin State,67.4,85.1,107.2,0.421,0.465,20.1,27.0,61.4,0.311,0.513,0.554,18.4,38.6,73.0,0.383
360,2023-24,Detroit Mercy,68.0,96.2,117.0,0.473,0.511,17.1,26.1,64.6,0.303,0.559,0.594,14.9,35.4,73.9,0.319
361,2023-24,Mississippi Valley State,66.2,83.4,116.8,0.425,0.461,21.0,27.9,64.3,0.330,0.556,0.588,14.7,35.7,72.1,0.416

In [11]:
MBB_Team_Ratings = pd.read_csv('C:\\Users\\jacks\\Documents\\GitHub\\MBB_Shiny_Dashboard\\Source_Data\\MBB_Ratings.csv')
MBB_Team_Ratings = MBB_Team_Ratings.drop(columns=['W', 'L', 'Rk', 'Unnamed: 3', 'Unnamed: 9', 'Unnamed: 11'])
MBB_Team_Ratings

,School,Conf,Pts,Opp,MOV,SOS,OSRS,DSRS,SRS,Adjusted ORtg,Adjusted DRtg,Adjusted NRtg
0,Connecticut,Big East,81.4,63.4,18.00,8.70,12.04,14.67,26.70,127.65,89.05,38.60
1,Houston,Big 12,73.5,57.6,15.89,9.80,6.19,19.50,25.69,120.40,81.96,38.45
2,Purdue,Big Ten,82.3,69.0,13.33,11.60,14.65,10.29,24.93,126.62,91.31,35.31
3,Arizona,Pac-12,87.1,72.1,15.08,9.45,18.59,5.95,24.54,122.12,89.17,32.95
4,Auburn,SEC,83.1,68.3,14.80,7.66,13.48,8.98,22.46,121.57,90.09,31.48
...,...,...,...,...,...,...,...,...,...,...,...,...
357,Stonehill,NEC,63.5,76.1,-12.68,-6.10,-11.89,-8.21,-20.10,88.62,116.38,-27.77
358,VMI,Southern,68.9,82.6,-13.75,-2.44,-6.75,-13.90,-20.65,86.59,113.81,-27.22
359,IUPUI,Horizon,65.9,79.8,-13.94,-4.62,-11.86,-9.45,-21.31,89.57,120.43,-30.86
360,Coppin State,MEAC,57.9,72.8,-14.97,-6.49,-17.64,-3.81,-21.46,81.63,112.41,-30.78
361,Mississippi Valley State,SWAC,55.5,77.7,-22.26,-3.91,-19.39,-6.78,-26.17,81.79,120.60,-38.80

In [12]:
output = db.query(
'''
select * from MBB_Team_totals t
inner join MBB_Opponent_Totals o
on t.Team=o.Team
inner join MBB_Team_Opponent_per_game p
on t.Team=p.Team
inner join MBB_Team_Advanced a
on t.Team=a.Team
inner join MBB_Team_Ratings r
on t.Team=r.School
'''
).to_df()

In [13]:
output['NCAA Tournament'] = 0

In [14]:
output['NCAA Tournament'] = output['Team'].apply(lambda x: str(x in made_tournament))

In [15]:
output

,Season,Team,W,G,L,W/L%,Team Total FG,Team Total FGA,Team Total 2P,Team Total 2PA,...,Opp,MOV,SOS,OSRS,DSRS,SRS,Adjusted ORtg,Adjusted DRtg,Adjusted NRtg,NCAA Tournament
0,2023-24,Purdue,34,39,5,0.872,1109,2272,791,1484,...,69.0,13.33,11.60,14.65,10.29,24.93,126.62,91.31,35.31,True
1,2023-24,Houston,32,37,5,0.865,981,2233,695,1412,...,57.6,15.89,9.80,6.19,19.50,25.69,120.40,81.96,38.45,True
2,2023-24,Indiana State,32,39,7,0.821,1141,2258,714,1139,...,73.2,11.67,2.26,13.21,0.23,13.44,119.38,100.75,18.63,False
3,2023-24,James Madison,32,36,4,0.889,1073,2254,766,1402,...,69.6,13.58,-3.75,7.33,0.87,8.19,111.21,100.04,11.18,True
4,2023-24,Grand Canyon,30,35,5,0.857,924,2008,679,1279,...,67.0,12.09,-0.52,5.21,5.24,10.45,111.56,96.28,15.28,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,2023-24,St. Mary's (CA),26,34,8,0.765,936,2007,678,1274,...,59.2,14.79,3.46,1.55,14.77,16.31,115.39,90.41,24.98,True
358,2023-24,Nebraska,23,34,11,0.676,912,2017,593,1124,...,70.9,6.82,7.53,9.11,5.24,14.36,115.91,95.53,20.38,True
359,2023-24,Long Beach State,21,36,15,0.583,993,2239,799,1602,...,76.0,1.42,-1.19,3.92,-5.11,-1.19,104.65,106.32,-1.68,True
360,2023-24,UC Davis,20,33,13,0.606,799,1808,569,1124,...,68.1,3.18,-2.85,-3.38,2.05,-1.33,100.84,102.68,-1.85,False
361,2023-24,North Texas,19,34,15,0.559,826,1907,542,1154,...,63.8,5.41,4.28,-3.08,11.49,8.41,109.98,97.27,12.71,False

In [16]:
db.query(
'''
select Team, School from MBB_Team_totals t
full outer join MBB_Team_Ratings r
on t.Team=r.School
where School is null
or Team is null
'''
).to_df()

Empty DataFrame
Columns: [Team, School]
Index: []

In [17]:
output['path'] = 'logos\\' + output['Team'].str.replace(' ', '-') + '.png'
output['image_name'] = output['Team'].str.replace(' ', '-').str.lower() + '.png'

In [30]:
shortened_output = [
'Season','Team','W','G','L','W/L%','Team Shooting Total FG%','Team Shooting Total 2P%','Team Shooting Total 3P%','Team Shooting Total FT%','Team Shooting Total TS%',
'Team Shooting Total eFG%','Opponent Shooting Total FG%','Opponent Shooting Total 2P%','Opponent Shooting Total 3P%','Opponent Shooting Total FT%','Team FG','Team FGA',
'Team 2P','Team 2PA','Team 3P','Team 3PA','Team FT','Team FTA','Team ORB','Team DRB','Team TRB','Team AST','Team STL','Team BLK','Team TOV','Team PF','Opponent FG','Opponent FGA',
'Opponent 2P','Opponent 2PA','Opponent 3P','Opponent 3PA','Opponent FT','Opponent FTA','Opponent ORB','Opponent DRB','Opponent TRB','Opponent AST','Opponent STL','Opponent BLK',
'Opponent TOV','Opponent PF','Miscellaneous Pace','Miscellaneous ORtg','Miscellaneous DRtg','Team TOV%','Team ORB%','Team DRB%','Team FTr','Opponent Shooting eFG%',
'Opponent Shooting TS%','Opponent TOV%','Opponent ORB%','Opponent DRB%','Opponent FTr','Conf','Pts','Opp','MOV','SOS','OSRS','DSRS','SRS','Adjusted ORtg','Adjusted DRtg',
'Adjusted NRtg','NCAA Tournament','path','image_name'
]

In [31]:
output[shortened_output].to_csv('C:\\Users\\jacks\\Documents\\GitHub\\MBB_Shiny_Dashboard\\Cleaned_Data\\Season_Stats_23_24.csv')

In [18]:
output.to_csv('C:\\Users\\jacks\\Documents\\GitHub\\MBB_Shiny_Dashboard\\Cleaned_Data\\Season_Stats_23_24.csv')

In [19]:
print(output.dtypes)

Season              object
Team                object
W                    int64
G                    int64
L                    int64
                    ...
Adjusted DRtg      float64
Adjusted NRtg      float64
NCAA Tournament     object
path                object
image_name          object
Length: 120, dtype: object

In [20]:
print(output['Conf'].unique())

['Big Ten' 'Big 12' 'MVC' 'Sun Belt' 'WAC' 'Southern' 'Pac-12' 'SEC' 'WCC'
 'OVC' 'MWC' 'ACC' 'A-10' 'AAC' 'Big West' 'MAAC' 'Big Sky' 'MEAC' 'Ivy'
 'Horizon' 'AEC' 'Big South' 'Summit' 'SWAC' 'NEC' 'CAA' 'Southland' 'MAC'
 'A-Sun' 'Big East' 'CUSA' 'Patriot' 'Ind']

In [21]:
output['Team Shooting Total 3P%'].mean()

0.33871270718232044

In [22]:
output['Team 2PA'].mean()

36.75027624309392

In [23]:
count_y = 0
count_n = 0
missing = []
for path in output['path']:
    if not os.path.isfile(path):
        count_n += 1
        missing.append(path)
    if os.path.isfile(path):
        count_y += 1
print('exist: ', count_y)
print('does not exist: ', count_n)
print(missing)

exist:  361
does not exist:  1
['logos\\Le-Moyne.png']

In [24]:
output['image_name']

0                purdue.png
1               houston.png
2         indiana-state.png
3         james-madison.png
4          grand-canyon.png
               ...
357     st.-mary's-(ca).png
358            nebraska.png
359    long-beach-state.png
360            uc-davis.png
361         north-texas.png
Name: image_name, Length: 362, dtype: object

In [29]:
print('[')
for o in output.columns:
    print(f"'{o}',")
print(']')

[
'Season',
'Team',
'W',
'G',
'L',
'W/L%',
'Team Total FG',
'Team Total FGA',
'Team Total 2P',
'Team Total 2PA',
'Team Total 3P',
'Team Total 3PA',
'Team Total FT',
'Team Total FTA',
'Team Total ORB',
'Team Total DRB',
'Team Total TRB',
'Team Total AST',
'Team Total STL',
'Team Total BLK',
'Team Total TOV',
'Team Total PF',
'Team Total PTS',
'Team Shooting Total FG%',
'Team Shooting Total 2P%',
'Team Shooting Total 3P%',
'Team Shooting Total FT%',
'Team Shooting Total TS%',
'Team Shooting Total eFG%',
'Season_2',
'Team_2',
'Opponent Total FG',
'Opponent Total FGA',
'Opponent Total 2P',
'Opponent Total 2PA',
'Opponent Total 3P',
'Opponent Total 3PA',
'Opponent Total FT',
'Opponent Total FTA',
'Opponent Total ORB',
'Opponent Total DRB',
'Opponent Total TRB',
'Opponent Total AST',
'Opponent Total STL',
'Opponent Total BLK',
'Opponent Total TOV',
'Opponent Total PF',
'Opponent Total PTS',
'Opponent Shooting Total FG%',
'Opponent Shooting Total 2P%',
'Opponent Shooting Total 3P%',
'Opponent Shooting Total FT%',
'Season_3',
'Team_3',
'Team FG',
'Team FGA',
'Team 2P',
'Team 2PA',
'Team 3P',
'Team 3PA',
'Team FT',
'Team FTA',
'Team ORB',
'Team DRB',
'Team TRB',
'Team AST',
'Team STL',
'Team BLK',
'Team TOV',
'Team PF',
'Team PTS',
'Opponent FG',
'Opponent FGA',
'Opponent 2P',
'Opponent 2PA',
'Opponent 3P',
'Opponent 3PA',
'Opponent FT',
'Opponent FTA',
'Opponent ORB',
'Opponent DRB',
'Opponent TRB',
'Opponent AST',
'Opponent STL',
'Opponent BLK',
'Opponent TOV',
'Opponent PF',
'Opponent PTS',
'Season_4',
'Team_4',
'Miscellaneous Pace',
'Miscellaneous ORtg',
'Miscellaneous DRtg',
'Team Shooting eFG%',
'Team Shooting TS%',
'Team TOV%',
'Team ORB%',
'Team DRB%',
'Team FTr',
'Opponent Shooting eFG%',
'Opponent Shooting TS%',
'Opponent TOV%',
'Opponent ORB%',
'Opponent DRB%',
'Opponent FTr',
'School',
'Conf',
'Pts',
'Opp',
'MOV',
'SOS',
'OSRS',
'DSRS',
'SRS',
'Adjusted ORtg',
'Adjusted DRtg',
'Adjusted NRtg',
'NCAA Tournament',
'path',
'image_name',
]

In [38]:
team_dict = {}
for conf in output['Conf'].unique().tolist():
    local_dict = {}
    for idx, i in enumerate(output[output['Conf']==conf]['Team'].to_list()):
        local_dict[i] = i
    team_dict[conf] = local_dict

In [39]:
team_dict

{'Big Ten': {'Purdue': 'Purdue',
  'Illinois': 'Illinois',
  'Northwestern': 'Northwestern',
  'Ohio State': 'Ohio State',
  'Wisconsin': 'Wisconsin',
  'Michigan State': 'Michigan State',
  'Minnesota': 'Minnesota',
  'Penn State': 'Penn State',
  'Michigan': 'Michigan',
  'Indiana': 'Indiana',
  'Rutgers': 'Rutgers',
  'Iowa': 'Iowa',
  'Maryland': 'Maryland',
  'Nebraska': 'Nebraska'},
 'Big 12': {'Houston': 'Houston',
  'Iowa State': 'Iowa State',
  'Brigham Young': 'Brigham Young',
  'Kansas': 'Kansas',
  'TCU': 'TCU',
  'Kansas State': 'Kansas State',
  'UCF': 'UCF',
  'Oklahoma State': 'Oklahoma State',
  'West Virginia': 'West Virginia',
  'Baylor': 'Baylor',
  'Cincinnati': 'Cincinnati',
  'Texas Tech': 'Texas Tech',
  'Texas': 'Texas',
  'Oklahoma': 'Oklahoma'},
 'MVC': {'Indiana State': 'Indiana State',
  'Drake': 'Drake',
  'Bradley': 'Bradley',
  'Belmont': 'Belmont',
  'Southern Illinois': 'Southern Illinois',
  'Evansville': 'Evansville',
  'Missouri State': 'Missouri State',
  'Illinois State': 'Illinois State',
  'Illinois–Chicago': 'Illinois–Chicago',
  'Murray State': 'Murray State',
  'Valparaiso': 'Valparaiso',
  'Northern Iowa': 'Northern Iowa'},
 'Sun Belt': {'James Madison': 'James Madison',
  'Arkansas State': 'Arkansas State',
  'Troy': 'Troy',
  'Louisiana': 'Louisiana',
  'Texas State': 'Texas State',
  'South Alabama': 'South Alabama',
  'Southern Mississippi': 'Southern Mississippi',
  'Georgia State': 'Georgia State',
  'Marshall': 'Marshall',
  'Louisiana–Monroe': 'Louisiana–Monroe',
  'Coastal Carolina': 'Coastal Carolina',
  'Old Dominion': 'Old Dominion',
  'Georgia Southern': 'Georgia Southern',
  'Appalachian State': 'Appalachian State'},
 'WAC': {'Grand Canyon': 'Grand Canyon',
  'Tarleton State': 'Tarleton State',
  'Seattle': 'Seattle',
  'UT Arlington': 'UT Arlington',
  'Stephen F. Austin': 'Stephen F. Austin',
  'Abilene Christian': 'Abilene Christian',
  'California Baptist': 'California Baptist',
  'Utah Valley': 'Utah Valley',
  'Utah Tech': 'Utah Tech',
  'Southern Utah': 'Southern Utah',
  'Texas–Rio Grande Valley': 'Texas–Rio Grande Valley'},
 'Southern': {'Samford': 'Samford',
  'Western Carolina': 'Western Carolina',
  'Chattanooga': 'Chattanooga',
  'UNC Greensboro': 'UNC Greensboro',
  'Furman': 'Furman',
  'Wofford': 'Wofford',
  'Mercer': 'Mercer',
  'The Citadel': 'The Citadel',
  'VMI': 'VMI',
  'East Tennessee State': 'East Tennessee State'},
 'Pac-12': {'Arizona': 'Arizona',
  'Colorado': 'Colorado',
  'Washington': 'Washington',
  'UCLA': 'UCLA',
  'Southern California': 'Southern California',
  'Stanford': 'Stanford',
  'California': 'California',
  'Oregon State': 'Oregon State',
  'Washington State': 'Washington State',
  'Oregon': 'Oregon',
  'Utah': 'Utah',
  'Arizona State': 'Arizona State'},
 'SEC': {'Auburn': 'Auburn',
  'South Carolina': 'South Carolina',
  'Kentucky': 'Kentucky',
  'Mississippi State': 'Mississippi State',
  'Texas A&M': 'Texas A&M',
  'Georgia': 'Georgia',
  'Ole Miss': 'Ole Miss',
  'Arkansas': 'Arkansas',
  'Vanderbilt': 'Vanderbilt',
  'Missouri': 'Missouri',
  'Tennessee': 'Tennessee',
  'Alabama': 'Alabama',
  'Florida': 'Florida',
  'Louisiana State': 'Louisiana State'},
 'WCC': {'Gonzaga': 'Gonzaga',
  'San Francisco': 'San Francisco',
  'Santa Clara': 'Santa Clara',
  'San Diego': 'San Diego',
  'Pepperdine': 'Pepperdine',
  'Loyola Marymount': 'Loyola Marymount',
  'Portland': 'Portland',
  'Pacific': 'Pacific',
  "St. Mary's (CA)": "St. Mary's (CA)"},
 'OVC': {'Morehead State': 'Morehead State',
  'Little Rock': 'Little Rock',
  'UT Martin': 'UT Martin',
  'Tennessee State': 'Tennessee State',
  'SIU Edwardsville': 'SIU Edwardsville',
  'Eastern Illinois': 'Eastern Illinois',
  'Tennessee Tech': 'Tennessee Tech',
  'Lindenwood': 'Lindenwood',
  'Southeast Missouri State': 'Southeast Missouri State',
  'Southern Indiana': 'Southern Indiana',
  'Western Illinois': 'Western Illinois'},
 'MWC': {'Nevada': 'Nevada',
  'New Mexico': 'New Mexico',
  'Boise State': 'Boise State',
  'UNLV': 'UNLV',
  'Wyoming': 'Wyoming',
  'Fresno State': 'Fresno State',
  'Air Force': 'Air Force',
  'San Jose State': 'San Jose State',
  'Utah State': 'Utah State',
  'San Diego State': 'San Diego State',
  'Colorado State': 'Colorado State'},
 'ACC': {'NC State': 'NC State',
  'Clemson': 'Clemson',
  'Virginia': 'Virginia',
  'Pittsburgh': 'Pittsburgh',
  'Syracuse': 'Syracuse',
  'Virginia Tech': 'Virginia Tech',
  'Miami (FL)': 'Miami (FL)',
  'Georgia Tech': 'Georgia Tech',
  'Notre Dame': 'Notre Dame',
  'Louisville': 'Louisville',
  'North Carolina': 'North Carolina',
  'Duke': 'Duke',
  'Wake Forest': 'Wake Forest',
  'Boston College': 'Boston College',
  'Florida State': 'Florida State'},
 'A-10': {'Dayton': 'Dayton',
  'Duquesne': 'Duquesne',
  'VCU': 'VCU',
  'Richmond': 'Richmond',
  "Saint Joseph's": "Saint Joseph's",
  'Massachusetts': 'Massachusetts',
  'St. Bonaventure': 'St. Bonaventure',
  'La Salle': 'La Salle',
  'George Washington': 'George Washington',
  'Fordham': 'Fordham',
  'Saint Louis': 'Saint Louis',
  'Rhode Island': 'Rhode Island',
  'Davidson': 'Davidson',
  'Loyola Chicago': 'Loyola Chicago',
  'George Mason': 'George Mason'},
 'AAC': {'South Florida': 'South Florida',
  'Memphis': 'Memphis',
  'Charlotte': 'Charlotte',
  'Temple': 'Temple',
  'Tulsa': 'Tulsa',
  'East Carolina': 'East Carolina',
  'Wichita State': 'Wichita State',
  'Tulane': 'Tulane',
  'Rice': 'Rice',
  'UTSA': 'UTSA',
  'Florida Atlantic': 'Florida Atlantic',
  'SMU': 'SMU',
  'UAB': 'UAB',
  'North Texas': 'North Texas'},
 'Big West': {'UC Irvine': 'UC Irvine',
  'Hawaii': 'Hawaii',
  'Cal State Northridge': 'Cal State Northridge',
  'UC Riverside': 'UC Riverside',
  'UC Santa Barbara': 'UC Santa Barbara',
  'Cal State Fullerton': 'Cal State Fullerton',
  'Cal State Bakersfield': 'Cal State Bakersfield',
  'Cal Poly': 'Cal Poly',
  'UC San Diego': 'UC San Diego',
  'Long Beach State': 'Long Beach State',
  'UC Davis': 'UC Davis'},
 'MAAC': {'Fairfield': 'Fairfield',
  "Saint Peter's": "Saint Peter's",
  'Marist': 'Marist',
  'Iona': 'Iona',
  'Niagara': 'Niagara',
  'Rider': 'Rider',
  'Canisius': 'Canisius',
  "Mount St. Mary's": "Mount St. Mary's",
  'Manhattan': 'Manhattan',
  'Siena': 'Siena',
  'Quinnipiac': 'Quinnipiac'},
 'Big Sky': {'Montana': 'Montana',
  'Eastern Washington': 'Eastern Washington',
  'Northern Colorado': 'Northern Colorado',
  'Montana State': 'Montana State',
  'Portland State': 'Portland State',
  'Idaho State': 'Idaho State',
  'Northern Arizona': 'Northern Arizona',
  'Idaho': 'Idaho',
  'Sacramento State': 'Sacramento State',
  'Weber State': 'Weber State'},
 'MEAC': {'Norfolk State': 'Norfolk State',
  'Howard': 'Howard',
  'North Carolina Central': 'North Carolina Central',
  'Delaware State': 'Delaware State',
  'South Carolina State': 'South Carolina State',
  'Morgan State': 'Morgan State',
  'Maryland Eastern Shore': 'Maryland Eastern Shore',
  'Coppin State': 'Coppin State'},
 'Ivy': {'Princeton': 'Princeton',
  'Yale': 'Yale',
  'Cornell': 'Cornell',
  'Harvard': 'Harvard',
  'Brown': 'Brown',
  'Dartmouth': 'Dartmouth',
  'Pennsylvania': 'Pennsylvania',
  'Columbia': 'Columbia'},
 'Horizon': {'Purdue Fort Wayne': 'Purdue Fort Wayne',
  'Youngstown State': 'Youngstown State',
  'Cleveland State': 'Cleveland State',
  'Robert Morris': 'Robert Morris',
  'IUPUI': 'IUPUI',
  'Detroit Mercy': 'Detroit Mercy',
  'Oakland': 'Oakland',
  'Milwaukee': 'Milwaukee',
  'Green Bay': 'Green Bay',
  'Northern Kentucky': 'Northern Kentucky',
  'Wright State': 'Wright State'},
 'AEC': {'UMass Lowell': 'UMass Lowell',
  'Bryant': 'Bryant',
  'New Hampshire': 'New Hampshire',
  'Binghamton': 'Binghamton',
  'Maine': 'Maine',
  'Albany (NY)': 'Albany (NY)',
  'UMBC': 'UMBC',
  'NJIT': 'NJIT',
  'Vermont': 'Vermont'},
 'Big South': {'UNC Asheville': 'UNC Asheville',
  'Longwood': 'Longwood',
  'Winthrop': 'Winthrop',
  'Radford': 'Radford',
  'Presbyterian': 'Presbyterian',
  'Charleston Southern': 'Charleston Southern',
  'USC Upstate': 'USC Upstate',
  'High Point': 'High Point',
  'Gardner-Webb': 'Gardner-Webb'},
 'Summit': {'South Dakota State': 'South Dakota State',
  'St. Thomas': 'St. Thomas',
  'North Dakota': 'North Dakota',
  'Denver': 'Denver',
  'Kansas City': 'Kansas City',
  'Omaha': 'Omaha',
  'North Dakota State': 'North Dakota State',
  'Oral Roberts': 'Oral Roberts',
  'South Dakota': 'South Dakota'},
 'SWAC': {'Grambling State': 'Grambling State',
  'Southern': 'Southern',
  'Bethune-Cookman': 'Bethune-Cookman',
  'Texas Southern': 'Texas Southern',
  'Jackson State': 'Jackson State',
  'Alcorn State': 'Alcorn State',
  'Alabama State': 'Alabama State',
  'Arkansas–Pine Bluff': 'Arkansas–Pine Bluff',
  'Alabama A&M': 'Alabama A&M',
  'Prairie View A&M': 'Prairie View A&M',
  'Florida A&M': 'Florida A&M',
  'Mississippi Valley State': 'Mississippi Valley State'},
 'NEC': {'Merrimack': 'Merrimack',
  'Central Connecticut State': 'Central Connecticut State',
  'Sacred Heart': 'Sacred Heart',
  'FDU': 'FDU',
  'Le Moyne': 'Le Moyne',
  'Saint Francis (PA)': 'Saint Francis (PA)',
  'LIU': 'LIU',
  'Stonehill': 'Stonehill',
  'Wagner': 'Wagner'},
 'CAA': {'UNC Wilmington': 'UNC Wilmington',
  'Drexel': 'Drexel',
  'Hofstra': 'Hofstra',
  'Stony Brook': 'Stony Brook',
  'Towson': 'Towson',
  'Delaware': 'Delaware',
  'Monmouth': 'Monmouth',
  'Campbell': 'Campbell',
  'Elon': 'Elon',
  'Northeastern': 'Northeastern',
  'Hampton': 'Hampton',
  'North Carolina A&T': 'North Carolina A&T',
  'William & Mary': 'William & Mary',
  'College of Charleston': 'College of Charleston'},
 'Southland': {'Texas A&M–Corpus Christi': 'Texas A&M–Corpus Christi',
  'Nicholls State': 'Nicholls State',
  'Lamar': 'Lamar',
  'Southeastern Louisiana': 'Southeastern Louisiana',
  'Texas A&M–Commerce': 'Texas A&M–Commerce',
  'New Orleans': 'New Orleans',
  'Northwestern State': 'Northwestern State',
  'Incarnate Word': 'Incarnate Word',
  'Houston Christian': 'Houston Christian',
  'McNeese State': 'McNeese State'},
 'MAC': {'Bowling Green': 'Bowling Green',
  'Toledo': 'Toledo',
  'Central Michigan': 'Central Michigan',
  'Kent State': 'Kent State',
  'Ball State': 'Ball State',
  'Miami (OH)': 'Miami (OH)',
  'Eastern Michigan': 'Eastern Michigan',
  'Western Michigan': 'Western Michigan',
  'Northern Illinois': 'Northern Illinois',
  'Buffalo': 'Buffalo',
  'Ohio': 'Ohio',
  'Akron': 'Akron'},
 'A-Sun': {'Lipscomb': 'Lipscomb',
  'Eastern Kentucky': 'Eastern Kentucky',
  'Jacksonville': 'Jacksonville',
  'North Florida': 'North Florida',
  'Kennesaw State': 'Kennesaw State',
  'Florida Gulf Coast': 'Florida Gulf Coast',
  'Queens (NC)': 'Queens (NC)',
  'Central Arkansas': 'Central Arkansas',
  'Bellarmine': 'Bellarmine',
  'Stetson': 'Stetson',
  'Austin Peay': 'Austin Peay',
  'North Alabama': 'North Alabama'},
 'Big East': {"St. John's (NY)": "St. John's (NY)",
  'Butler': 'Butler',
  'Villanova': 'Villanova',
  'Georgetown': 'Georgetown',
  'DePaul': 'DePaul',
  'Providence': 'Providence',
  'Xavier': 'Xavier',
  'Connecticut': 'Connecticut',
  'Marquette': 'Marquette',
  'Creighton': 'Creighton',
  'Seton Hall': 'Seton Hall'},
 'CUSA': {'Liberty': 'Liberty',
  'UTEP': 'UTEP',
  'Jacksonville State': 'Jacksonville State',
  'Middle Tennessee': 'Middle Tennessee',
  'New Mexico State': 'New Mexico State',
  'Florida International': 'Florida International',
  'Louisiana Tech': 'Louisiana Tech',
  'Western Kentucky': 'Western Kentucky',
  'Sam Houston State': 'Sam Houston State'},
 'Patriot': {'American': 'American',
  'Boston University': 'Boston University',
  'Bucknell': 'Bucknell',
  'Lehigh': 'Lehigh',
  'Navy': 'Navy',
  'Lafayette': 'Lafayette',
  'Army': 'Army',
  'Holy Cross': 'Holy Cross',
  'Loyola (MD)': 'Loyola (MD)',
  'Colgate': 'Colgate'},
 'Ind': {'Chicago State': 'Chicago State'}}